services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - AUTH_SECRET=${AUTH_SECRET}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
