services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
