/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Startup = {
  _id: string
  _type: 'startup'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  views?: number
  description?: string
  category?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  pitch?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  id?: number
  name?: string
  username?: string
  email?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  bio?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Markdown = string

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Startup
  | Slug
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Markdown
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/lib/queries.ts
// Variable: STARTUPS_QUERY
// Query: *[_type == 'startup' && (!defined($q) || title match $q || author->name match $q || category match $q) ]{    'slug': slug.current,    title,     description,     'imageAlt': image.alt,     'imageUrl':image.asset -> .url,    category,     views,     _createdAt,    author->{        id,        name,        'imageAlt': image.alt,        'imageUrl': image.asset -> .url,      },}
export type STARTUPS_QUERYResult = Array<{
  slug: string | null
  title: string | null
  description: string | null
  imageAlt: string | null
  imageUrl: string | null
  category: string | null
  views: number | null
  _createdAt: string
  author: {
    id: number | null
    name: string | null
    imageAlt: string | null
    imageUrl: string | null
  } | null
}>
// Variable: STARTUP_DETAILS_QUERY
// Query: *[_type == 'startup' && slug.current == $slug ][0]{    'slug': slug.current,    title,     description,     'imageAlt': image.alt,     'imageUrl':image.asset -> .url,    category,     views,     _createdAt,    pitch,    author->{        id,        name,        username,        'imageAlt': image.alt,        'imageUrl': image.asset -> .url,      },}
export type STARTUP_DETAILS_QUERYResult = {
  slug: string | null
  title: string | null
  description: string | null
  imageAlt: string | null
  imageUrl: string | null
  category: string | null
  views: number | null
  _createdAt: string
  pitch: string | null
  author: {
    id: number | null
    name: string | null
    username: string | null
    imageAlt: string | null
    imageUrl: string | null
  } | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    "*[_type == 'startup' && (!defined($q) || title match $q || author->name match $q || category match $q) ]{\n    'slug': slug.current,\n    title, \n    description, \n    'imageAlt': image.alt, \n    'imageUrl':image.asset -> .url,\n    category, \n    views, \n    _createdAt,\n    author->{\n        id,\n        name,\n        'imageAlt': image.alt,\n        'imageUrl': image.asset -> .url,  \n    },\n}": STARTUPS_QUERYResult
    "*[_type == 'startup' && slug.current == $slug ][0]{\n    'slug': slug.current,\n    title, \n    description, \n    'imageAlt': image.alt, \n    'imageUrl':image.asset -> .url,\n    category, \n    views, \n    _createdAt,\n    pitch,\n    author->{\n        id,\n        name,\n        username,\n        'imageAlt': image.alt,\n        'imageUrl': image.asset -> .url,  \n    },\n}": STARTUP_DETAILS_QUERYResult
  }
}
