export const categoriesList = [
  { title: 'AI & Robotics', value: 'ai-robotics' },
  { title: 'E-commerce', value: 'ecommerce' },
  { title: 'Education', value: 'education' },
  { title: 'Fashion & Style', value: 'fashion-style' },
  { title: 'Finance & Crypto', value: 'finance-crypto' },
  { title: 'Food & Beverage', value: 'food-beverage' },
  { title: 'Gaming', value: 'gaming' },
  { title: 'Health & Wellness', value: 'health-wellness' },
  { title: 'Logistics', value: 'logistics' },
  { title: 'Marketing', value: 'marketing' },
  { title: 'PropTech', value: 'proptech' },
  { title: 'Renewable Energy', value: 'renewable-energy' },
  { title: 'Sustainability', value: 'sustainability' },
  { title: 'Technology', value: 'technology' },
  { title: 'Travel & Tourism', value: 'travel-tourism' },
]
